@server = http://localhost:3000

POST {{server}}
Content-Type: multipart/form-data; boundary=file

--file--
Content-Disposition: form-data; name="file"; filename="file"

Cras volutpat nibh congue metus tempor congue.
--file--
###
POST {{server}}
Content-Type: multipart/form-data; boundary=file

--file--
Content-Disposition: form-data; name="file"; filename="file"

< app.test.txt
--file--
###
POST {{server}}
Content-Type: multipart/form-data; boundary=file

--file--
Content-Disposition: form-data; name="file"; filename="file.png"
Content-Type: image/png

< app.test.png
--file--